<?php

namespace GraphQL\SchemaObject;

use GraphQL\Exception\EmptySelectionSetException;
use GraphQL\Mutation;
use GraphQL\MutationBuilder\AbstractMutationBuilder;

/**
 * An abstract class that acts as the base for all schema query objects generated by the SchemaClassGenerator
 *
 * Class MutationObject
 *
 * @package GraphQL\SchemaObject
 */
abstract class MutationObject extends AbstractMutationBuilder
{
    /**
     * This constant stores the name to be given to the root mutation object
     *
     * @var  string
     */
    public const ROOT_MUTATION_OBJECT_NAME = 'Root';

    /**
     * This constant stores the name of the object name in the API definition
     *
     * @var string
     */
    protected const OBJECT_NAME = '';

    /**
     * SchemaObject constructor.
     *
     * @param string $fieldName
     */
    public function __construct(string $fieldName = '')
    {
        // Maintain backwards compatibility for generated RootMutationObjects by converting OBJECT_NAME 'mutation' to '' when encountered
        // TODO: Remove this when bumping up one major version
        $objectName = static::OBJECT_NAME === 'mutation' ? '' : static::OBJECT_NAME;
        $queryObject = !empty($fieldName) ? $fieldName : $objectName;
        parent::__construct($queryObject);
    }

    /**
     * @param array $arguments
     *
     * @return $this
     */
    protected function appendArguments(array $arguments): MutationObject
    {
        foreach ($arguments as $argName => $argValue) {
            if ($argValue instanceof InputObject) {
                $argValue = $argValue->toRawObject();
            }

            $this->setArgument($argName, $argValue);
        }

        return $this;
    }

    /**
     * @return Mutation
     */
    public function getMutation(): Mutation
    {
        return parent::getMutation();
    }
}